name: Release RustOwl

on:
  push:
    tags:
      - v*

jobs:
  check:
    uses: ./.github/workflows/check.yaml

  extension:
    runs-on: ubuntu-latest
    needs:
      - check
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install --frozen-locked
        working-directory: ./vscode
      - name: Create VSIX
        run: yarn build
        working-directory: ./vscode
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: auto RustOwl update
          files: |
            ./vscode/**/*.vsix
            ./rustowl/install.sh
          draft: true

  binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: test build rust project
        uses: lxl66566/rust-simple-release@v0.2.4
        with:
          targets: |
            aarch64-unknown-linux-gnu
            aarch64-unknown-linux-musl
            x86_64-pc-windows-msvc
            x86_64-unknown-linux-musl
            x86_64-unknown-linux-gnu
            aarch64-apple-darwin
            x86_64-apple-darwin

          token: ${{ secrets.GH_TOKEN }}
